package e2p.icotp.util.custom.pdf;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import e2p.icotp.App;
import e2p.icotp.model.Payment;
import e2p.icotp.util.FileUtil;
import e2p.icotp.util.custom.date.DateUtil;

public class InvoiceGenerator {
        static App app;
        static Payment payment;

        private static String file_name = "";
        private static String path_name = "";

        private static Font catFont = new Font(Font.FontFamily.HELVETICA, 18,
                        Font.BOLD);
        private static Font subFont = new Font(Font.FontFamily.HELVETICA, 12,
                        Font.NORMAL);
        private static Font smallBold = new Font(Font.FontFamily.HELVETICA, 12,
                        Font.BOLD);

        public static void generate_invoice(App val1, Payment val2) throws Exception {
                app = val1;
                payment = val2;

                file_name = FileUtil.CUSTOM_DIR + payment.getLoaner_id().getLoaner_id() +
                                FileUtil.FS + payment.getLoan_id().getLoan_id() + FileUtil.FS + "invoices" + FileUtil.FS
                                + payment.getPayment_id()
                                + ".pdf";

                path_name = FileUtil.CUSTOM_DIR + payment.getLoaner_id().getLoaner_id() +
                                FileUtil.FS + payment.getLoan_id().getLoan_id() + FileUtil.FS + "invoices"
                                + FileUtil.FS;

                System.out.println(file_name);
                create_new_file(file_name, path_name);
                try {
                        Document document = new Document();
                        PdfWriter.getInstance(document,
                                        new FileOutputStream(file_name));
                        document.open();
                        addMetaData(document);
                        addTitlePage(document);
                        addTable(document);
                        addContent(document);
                        document.close();
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        private static void addMetaData(Document document) {
                document.addTitle("Invoice for Payment No. " + payment.getPayment_id());
                document.addSubject("Payment");
                document.addKeywords(
                                payment.getLoaner_id().getLoaner_id() + ", " + payment.getLoan_id().getLoan_id() + ", "
                                                + payment.getPayment_id());
                document.addAuthor("Zephyr LMS");
                document.addCreator("Zephyr LMS");

        }

        private static void addTitlePage(Document document) throws DocumentException {
                Paragraph preface = new Paragraph();
                // We add one empty line
                addEmptyLine(preface, 1);
                // Lets write a big header
                StringBuilder payment_loan_type = new StringBuilder();
                payment_loan_type.append(payment.getLoan_id().getLoanType().getName().get());
                payment_loan_type.delete(payment_loan_type.length() - 1, payment_loan_type.length());
                Paragraph invoice_title = new Paragraph(
                                "Zephyr Loans                                                           "
                                                + payment_loan_type.toString(),
                                catFont);
                // invoice_title.setAlignment(Element.ALIGN_CENTER);
                invoice_title.getFont().setSize(17.0f);
                preface.add(invoice_title);

                addEmptyLine(preface, 1);
                // Will create: Report generated by: _name, _date
                preface.add(new Paragraph(
                                "Report generated by: " + "Zephyr LMS" + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                                smallBold));
                // addEmptyLine(preface, 3);

                Paragraph am = new Paragraph(new Paragraph(
                                payment.getLoaner_id().getName() + ": " + payment.getPayment_amount(),
                                subFont));

                preface.add(am);

                addEmptyLine(am, 1);
                document.add(preface);
        }

        private static void addTable(Document document) throws DocumentException {
                // Create a table with 3 columns
                PdfPTable table = new PdfPTable(2);

                // Add table header
                PdfPCell header1 = new PdfPCell(new Paragraph("Payment ID"));
                PdfPCell header2 = new PdfPCell(new Paragraph("Loan ID"));
                PdfPCell header3 = new PdfPCell(new Paragraph("Due Date"));
                PdfPCell header4 = new PdfPCell(new Paragraph("Payment Date"));
                PdfPCell header5 = new PdfPCell(new Paragraph("Payment Due"));
                PdfPCell header6 = new PdfPCell(new Paragraph("Paid"));
                PdfPCell header_blank1 = new PdfPCell(new Paragraph(""));
                PdfPCell header7 = new PdfPCell(new Paragraph("Total Balance"));
                PdfPCell header8 = new PdfPCell(new Paragraph("Total Paid"));

                table.addCell(header1);
                table.addCell(payment.getPayment_id() + "");
                table.addCell(header2);
                table.addCell(payment.getLoan_id().getLoan_id() + "");
                table.addCell(header3);
                table.addCell(DateUtil.localizeDateProperty(payment.getLoan_id().getNextDueDate()).get());
                table.addCell(header4);
                table.addCell(DateUtil.localizeDate(payment.getDatePaymentProperty().get()));
                table.addCell(header5);
                table.addCell("$" + payment.getLoan_id().getNextPaymentProperty().get() + "");
                table.addCell(header6);
                table.addCell("$" + payment.getPayment_amount() + "");
                table.addCell(header_blank1);
                table.addCell(header_blank1);
                table.addCell(header7);
                table.addCell("$" + payment.getLoan_id().getBalance() + "");
                table.addCell(header8);
                table.addCell("$" + payment.getLoan_id().getPaid() + "");
                // table.addCell(payment.);

                document.add(table);

        }

        private static void addContent(Document document) {
        }

        private static void addEmptyLine(Paragraph paragraph, int number) {
                for (int i = 0; i < number; i++) {
                        paragraph.add(new Paragraph(" "));
                }
        }

        private static void create_new_file(String file_name, String path_name) throws Exception {
                FileUtil.create_dir(path_name);
                File destination = new File(file_name);
        }
}
